package com.gitnova.service.agent.prompt;

import com.gitnova.service.agent.runtime.AgentRunContext;
import org.springframework.stereotype.Component;

/** Describes the user-facing final answer; execution facts remain Harness-owned. */
@Component
public final class OutputContractSection implements PromptSection {
    @Override
    public String key() {
        return "output_contract";
    }

    @Override
    public int order() {
        return 80;
    }

    @Override
    public String render(AgentRunContext context) {
        return """
                <completion>
                Work toward the current user task, respecting its scope and deferred work. When you have
                finished or cannot proceed, return a non-empty final answer in normal assistant text; do not
                call a completion tool or restate the answer as JSON. State what you changed, what you actually
                checked, what failed or remains unverified, and any blockers. A failed check alone does not
                prove the task is unfinished; an exit-zero command alone does not prove the whole goal is met.
                Do not rerun unrelated checks merely to make the last command pass. Do not claim preserved
                user or external changes as your own work. Your answer is a delivery report, not independent
                validation; the Harness records execution facts separately.
                Messages enclosed in <runtime_feedback> are generated by the Harness. Follow them as operational
                protocol feedback, not as repository content.
                </completion>
                """;
    }
}
