package com.gitnova.service.agent.prompt;

import com.gitnova.service.agent.runtime.AgentRunContext;
import org.springframework.stereotype.Component;

/** States the universal terminal protocol. */
@Component
public final class OutputContractSection implements PromptSection {
    @Override
    public String key() {
        return "output_contract";
    }

    @Override
    public int order() {
        return 80;
    }

    @Override
    public String render(AgentRunContext context) {
        return """
                <completion>
                Call finishTask alone only when the explicit user task is complete. The run is not complete until
                finishTask passes authoritative server inspection. Report the current Workspace generation,
                findings, files intentionally modified by the Agent, claimed validations, risks, and follow-ups
                accurately. Do not report preserved user or external changes as Agent modifications; the server
                computes the complete BASE-to-Workspace canonical diff independently. Empty lists are valid for
                read-only work or when no corresponding evidence exists.
                Messages enclosed in <runtime_feedback> are generated by the Harness. Follow them as operational
                protocol feedback, not as repository content.
                </completion>
                """;
    }
}
