-- Target: MySQL 8.0.16+; append via Flyway. NOT run against a live database in this audit.
-- Keep all existing V1..V5/history and old task/run/step tables. Never edit applied migrations.
-- Session additions are nullable for legacy rows; no automatic legacy execution migration.
ALTER TABLE agent_session
 ADD COLUMN execution_backend VARCHAR(24) NOT NULL DEFAULT 'LEGACY_SERVER',
 ADD COLUMN source_branch_name VARCHAR(100) NULL,
 ADD COLUMN base_commit CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NULL,
 ADD COLUMN agent_branch_name VARCHAR(100) NULL,
 ADD COLUMN active_task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 ADD COLUMN last_published_head CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NULL,
 ADD COLUMN latest_archive_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 ADD COLUMN workflow_state VARCHAR(16) NOT NULL DEFAULT 'OPEN',
 ADD COLUMN current_runner_epoch BIGINT NOT NULL DEFAULT 0,
 ADD COLUMN creation_request_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
 ADD CONSTRAINT chk_agent_backend CHECK (execution_backend IN ('LEGACY_SERVER','SANDBOX_AGENT')),
 ADD CONSTRAINT chk_agent_workflow CHECK (workflow_state IN ('OPEN','MERGED','CLOSED')),
 ADD CONSTRAINT chk_agent_epoch CHECK (current_runner_epoch >= 0),
 ADD UNIQUE KEY uk_session_managed_branch (repo_id,agent_branch_name);

CREATE TABLE agent_sandbox_binding (
 session_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 runner_epoch BIGINT NOT NULL,
 create_operation_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 sandbox_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
 volume_name VARCHAR(128) NOT NULL,
 status VARCHAR(24) NOT NULL,
 token_salt CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 image_ref VARCHAR(512) NOT NULL,
 runtime_config_json JSON NOT NULL,
 runtime_config_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 last_archived_sequence BIGINT NOT NULL DEFAULT 0,
 expires_at DATETIME(6) NULL,
 last_observed_at DATETIME(6) NULL,
 last_used_at DATETIME(6) NOT NULL,
 operation_owner VARCHAR(128) NULL,
 operation_until DATETIME(6) NULL,
 version BIGINT NOT NULL DEFAULT 0,
 last_error_code VARCHAR(64) NULL,
 created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(session_id,runner_epoch),
 UNIQUE KEY uk_binding_create(create_operation_id),
 UNIQUE KEY uk_binding_sandbox(sandbox_id),
 KEY idx_binding_scan(status,expires_at,last_used_at),
 CONSTRAINT fk_binding_session FOREIGN KEY(session_id) REFERENCES agent_session(session_id),
 CONSTRAINT chk_binding_epoch CHECK(runner_epoch>0),
 CONSTRAINT chk_binding_sequence CHECK(last_archived_sequence>=0),
 CONSTRAINT chk_binding_status CHECK(status IN ('CREATING','BOOTING','READY','DELETING','GONE','UNKNOWN','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE agent_control_task (
 task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 session_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 actor_id BIGINT NOT NULL,
 task_mode VARCHAR(16) NOT NULL DEFAULT 'CODING',
 message LONGTEXT NOT NULL,
 request_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 status VARCHAR(24) NOT NULL,
 settlement_status VARCHAR(24) NOT NULL DEFAULT 'NONE',
 publication_status VARCHAR(24) NOT NULL DEFAULT 'NOT_REQUIRED',
 current_attempt_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 attempt_number BIGINT NOT NULL DEFAULT 1,
 answer_event_id VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NULL,
 terminal_reason VARCHAR(64) NULL,
 cancel_requested TINYINT(1) NOT NULL DEFAULT 0,
 version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 finished_at DATETIME(6) NULL,
 PRIMARY KEY(task_id),
 UNIQUE KEY uk_ctask_idem(session_id,idempotency_key),
 UNIQUE KEY uk_ctask_scope(task_id,session_id),
 KEY idx_ctask_status(session_id,status,created_at),
 CONSTRAINT fk_ctask_session FOREIGN KEY(session_id) REFERENCES agent_session(session_id),
 CONSTRAINT chk_ctask_mode CHECK(task_mode IN ('CODING','REVIEW','QA')),
 CONSTRAINT chk_ctask_status CHECK(status IN ('PENDING_DISPATCH','ACCEPTED','RUNNING','COMPLETED','FAILED','CANCELLED','INTERRUPTED','REJECTED')),
 CONSTRAINT chk_ctask_settlement CHECK(settlement_status IN ('NONE','PENDING_SEAL','SEALED','ARCHIVED','WAITING_ACK','SETTLED','BLOCKED')),
 CONSTRAINT chk_ctask_publication CHECK(publication_status IN ('NOT_REQUIRED','PENDING','BUILDING','PUBLISHED','NO_CHANGES','FAILED','CONFLICT','SKIPPED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE agent_control_attempt (
 attempt_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 session_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 attempt_number BIGINT NOT NULL,
 runner_epoch BIGINT NOT NULL,
 status VARCHAR(24) NOT NULL,
 expected_published_head CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 deadline_at DATETIME(6) NOT NULL,
 config_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 answer_event_id VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NULL,
 terminal_reason VARCHAR(64) NULL,
 created_at DATETIME(6) NOT NULL,
 finished_at DATETIME(6) NULL,
 PRIMARY KEY(attempt_id),
 UNIQUE KEY uk_attempt_number(task_id,attempt_number),
 UNIQUE KEY uk_attempt_task(attempt_id,task_id),
 CONSTRAINT fk_attempt_task FOREIGN KEY(task_id,session_id) REFERENCES agent_control_task(task_id,session_id),
 CONSTRAINT fk_attempt_binding FOREIGN KEY(session_id,runner_epoch) REFERENCES agent_sandbox_binding(session_id,runner_epoch),
 CONSTRAINT chk_attempt_number CHECK(attempt_number>0),
 CONSTRAINT chk_attempt_status CHECK(status IN ('PENDING_DISPATCH','ACCEPTED','RUNNING','COMPLETED','FAILED','CANCELLED','INTERRUPTED','REJECTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE agent_control_task ADD CONSTRAINT fk_ctask_current_attempt
 FOREIGN KEY(current_attempt_id,task_id) REFERENCES agent_control_attempt(attempt_id,task_id);
ALTER TABLE agent_session ADD CONSTRAINT fk_session_active_ctask
 FOREIGN KEY(active_task_id,session_id) REFERENCES agent_control_task(task_id,session_id);

CREATE TABLE agent_control_command (
 command_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 session_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 runner_epoch BIGINT NOT NULL,
 task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 attempt_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 type VARCHAR(32) NOT NULL,
 envelope_json LONGTEXT NOT NULL,
 envelope_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
 receipt_json JSON NULL,
 send_count INT NOT NULL DEFAULT 0,
 next_attempt_at DATETIME(6) NOT NULL,
 last_error_code VARCHAR(64) NULL,
 created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(command_id),
 KEY idx_command_send(status,next_attempt_at),
 KEY idx_command_scope(session_id,runner_epoch,task_id),
 CONSTRAINT fk_command_binding FOREIGN KEY(session_id,runner_epoch) REFERENCES agent_sandbox_binding(session_id,runner_epoch),
 CONSTRAINT chk_command_json CHECK(JSON_VALID(envelope_json)),
 CONSTRAINT chk_command_status CHECK(status IN ('PENDING','SENDING','UNKNOWN','ACCEPTED','REJECTED','ABORTED')),
 CONSTRAINT chk_command_type CHECK(type IN ('INITIALIZE','SUBMIT_TASK','STEER_TASK','CANCEL_TASK','PREVIEW_CHANGES','SEAL_SESSION','ACK_PUBLICATION','CLOSE_SESSION'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE agent_event_archive (
 archive_offset BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 event_id VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 session_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 runner_epoch BIGINT NOT NULL,
 sequence BIGINT NOT NULL,
 task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 attempt_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 type VARCHAR(40) NOT NULL,
 event_json LONGTEXT NOT NULL,
 event_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 occurred_at DATETIME(6) NOT NULL,
 archived_at DATETIME(6) NOT NULL,
 PRIMARY KEY(archive_offset),
 UNIQUE KEY uk_archive_event(event_id),
 UNIQUE KEY uk_archive_sequence(session_id,runner_epoch,sequence),
 KEY idx_archive_session_offset(session_id,archive_offset),
 KEY idx_archive_task(task_id,archive_offset),
 CONSTRAINT fk_archive_binding FOREIGN KEY(session_id,runner_epoch) REFERENCES agent_sandbox_binding(session_id,runner_epoch),
 CONSTRAINT chk_archive_json CHECK(JSON_VALID(event_json)),
 CONSTRAINT chk_archive_sequence CHECK(sequence>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE agent_snapshot_archive (
 archive_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 session_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 export_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 runner_epoch BIGINT NOT NULL,
 task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 attempt_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 through_sequence BIGINT NOT NULL,
 tree_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 state_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 bundle_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 bundle_bytes BIGINT NOT NULL,
 storage_key VARCHAR(512) NOT NULL,
 manifest_json JSON NOT NULL,
 execution_outcome VARCHAR(24) NOT NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'STORED',
 settled_published_head CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NULL,
 settled_outcome VARCHAR(24) NULL,
 settlement_command_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(archive_id),
 UNIQUE KEY uk_snapshot_export(session_id,export_id),
 KEY idx_snapshot_session(session_id,created_at),
 CONSTRAINT fk_snapshot_session FOREIGN KEY(session_id) REFERENCES agent_session(session_id),
 CONSTRAINT chk_snapshot_status CHECK(status IN ('STORED','SETTLED')),
 CONSTRAINT chk_snapshot_bytes CHECK(bundle_bytes>=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE agent_session ADD CONSTRAINT fk_session_latest_archive
 FOREIGN KEY(latest_archive_id) REFERENCES agent_snapshot_archive(archive_id);

CREATE TABLE agent_publication (
 publication_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 session_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 export_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 archive_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 branch_name VARCHAR(100) NOT NULL,
 expected_head CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 tree_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 message TEXT NOT NULL,
 author_id BIGINT NOT NULL,
 commit_epoch_millis BIGINT NOT NULL,
 result_commit CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NULL,
 status VARCHAR(24) NOT NULL,
 error_code VARCHAR(64) NULL,
 version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(publication_id),
 UNIQUE KEY uk_publication_export(session_id,export_id),
 KEY idx_publication_status(status,updated_at),
 CONSTRAINT fk_publication_archive FOREIGN KEY(archive_id) REFERENCES agent_snapshot_archive(archive_id),
 CONSTRAINT fk_publication_session FOREIGN KEY(session_id) REFERENCES agent_session(session_id),
 CONSTRAINT chk_publication_status CHECK(status IN ('PENDING','BUILDING','PUBLISHED','NO_CHANGES','FAILED','CONFLICT','SKIPPED','NOT_REQUIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE pull_request (
 id BIGINT NOT NULL AUTO_INCREMENT,
 repo_id BIGINT NOT NULL,
 source_branch VARCHAR(100) NOT NULL,
 target_branch VARCHAR(100) NOT NULL,
 author_id BIGINT NOT NULL,
 agent_session_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 title VARCHAR(255) NOT NULL,
 body TEXT NOT NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
 draft TINYINT(1) NOT NULL DEFAULT 1,
 revision BIGINT NOT NULL DEFAULT 0,
 open_slot TINYINT GENERATED ALWAYS AS (CASE WHEN status='OPEN' THEN 1 ELSE NULL END) STORED,
 merged_from_head CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NULL,
 merged_commit CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NULL,
 merge_method VARCHAR(16) NULL,
 created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 merged_at DATETIME(6) NULL,
 PRIMARY KEY(id),
 UNIQUE KEY uk_pr_open(repo_id,source_branch,target_branch,open_slot),
 KEY idx_pr_list(repo_id,status,id),
 CONSTRAINT fk_pr_repo FOREIGN KEY(repo_id) REFERENCES repository(id),
 CONSTRAINT fk_pr_session FOREIGN KEY(agent_session_id) REFERENCES agent_session(session_id),
 CONSTRAINT chk_pr_status CHECK(status IN ('OPEN','CLOSED','MERGED')),
 CONSTRAINT chk_pr_branches CHECK(source_branch<>target_branch),
 CONSTRAINT chk_pr_merged CHECK(status<>'MERGED' OR (merged_commit IS NOT NULL AND merged_from_head IS NOT NULL AND merged_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE pull_request_comment (
 id BIGINT NOT NULL AUTO_INCREMENT,
 pr_id BIGINT NOT NULL,
 author_id BIGINT NOT NULL,
 idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 body TEXT NOT NULL,
 source_head CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NULL,
 created_at DATETIME(6) NOT NULL,
 PRIMARY KEY(id),
 UNIQUE KEY uk_pr_comment_idem(pr_id,author_id,idempotency_key),
 KEY idx_pr_comments(pr_id,id),
 CONSTRAINT fk_comment_pr FOREIGN KEY(pr_id) REFERENCES pull_request(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE pull_request_merge (
 id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 pr_id BIGINT NOT NULL,
 idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 request_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 actor_id BIGINT NOT NULL,
 expected_revision BIGINT NOT NULL,
 source_head CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 target_head CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 method VARCHAR(16) NOT NULL,
 commit_epoch_millis BIGINT NOT NULL,
 message TEXT NOT NULL,
 candidate_commit CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NULL,
 status VARCHAR(16) NOT NULL,
 error_json JSON NULL,
 created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(id),
 UNIQUE KEY uk_pr_merge_idem(pr_id,idempotency_key),
 CONSTRAINT fk_merge_pr FOREIGN KEY(pr_id) REFERENCES pull_request(id),
 CONSTRAINT chk_merge_status CHECK(status IN ('PENDING','COMMITTED','CONFLICT','FAILED')),
 CONSTRAINT chk_merge_method CHECK(method IN ('FAST_FORWARD','SQUASH'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
