package com.gitnova.service.agent.runtime;

public enum AgentTerminationReason {FINALIZE_SUCCEEDED,
    MODEL_STOPPED_WITHOUT_FINALIZE,
    MODEL_OUTPUT_LENGTH,
    MODEL_CONTENT_FILTERED,
    MAX_MODEL_CALLS_REACHED,
    MAX_TOOL_CALLS_REACHED,
    MODEL_GATEWAY_FAILURE,
    INVALID_MODEL_PROTOCOL,
    MIXED_TERMINAL_TOOL_CALLS
}
