package com.gitnova.agent.protocol.event;

public enum EventType {
 COMMAND_ACCEPTED, TASK_STARTED, USER_MESSAGE_RECEIVED,
 MODEL_CALL_STARTED, MODEL_RESPONSE, TOOL_STARTED, TOOL_RESULT,
 CONTEXT_SUMMARY_CREATED, HARNESS_FEEDBACK, STEER_APPLIED,
 ANSWER_DELIVERED, TASK_FINISHED, SNAPSHOT_SEALED, TURN_SETTLED,
 PREVIEW_READY, RECOVERY_INTERRUPTED, WORKER_READY, WORKER_STOPPING
}
