package com.gitnova.service.agent.persistence;

/** Stable semantic type of one append-only durable Agent event. */
public enum AgentStepType {
    SESSION_CREATED,
    WORKSPACE_MATERIALIZED,
    WORKSPACE_PROVISIONING_FAILED,
    USER_MESSAGE_RECEIVED,
    TASK_CREATED,
    RUN_QUEUED,
    RUN_CLAIMED,
    RUN_LEASE_EXPIRED,
    RUN_TAKEN_OVER,
    RUN_COMPLETED,
    RUN_PARTIAL,
    RUN_FAILED,
    RUN_CANCELLED,
    TASK_RUN_FAILED,
    TASK_WAITING_USER,
    TASK_COMPLETED,
    TASK_FAILED,
    TASK_CANCELLED,
    MODEL_CALL_STARTED,
    MODEL_RESPONSE,
    TOOL_RESULT,
    HARNESS_FEEDBACK,
    COMPLETION_DECISION
}
